### ISSUE TITLE
Error when saving the configuration details

### ISSUE THREAD

**Issue by alextakitani** [cmuench/ulauncher-todoist#2]
I've entered my api key and got this error:

Tried to generate a new key and got the same error.

Message: 'com.github.cmuench.ulauncher-todoist'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.cmuench.ulauncher-todoist'

```

**Comment by cmuench** [comment]
Looks like a upstream problem in Ulauncher.

https://github.com/Ulauncher/Ulauncher/issues/418

**Comment by dolpa** [comment]
Same
Getting error
`Message: 'com.github.cmuench.ulauncher-todoist'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.cmuench.ulauncher-todoist'

````

**Comment by antelio** [comment]
reading the documentation, just:

pip3 install todoist-python

will fix.

**Comment by dolpa** [comment]
Worked for me. Thanks
