### ISSUE TITLE
Error saving api key

### ISSUE THREAD

**Issue by mateo-leal** [cmuench/ulauncher-todoist#3]
Message: 'com.github.cmuench.ulauncher-todoist'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.cmuench.ulauncher-todoist'

```

**Comment by cmuench** [comment]
Duplicate to #2.

**Comment by coreqode** [comment]
![image](https://user-images.githubusercontent.com/18486587/106012221-351e0500-60e1-11eb-8027-7f5ff84dc642.png)

Can not copy the api key. I am using ubuntu 20.04.

**Comment by cmuench** [comment]
@coreqode Thanks. Can you provide an stacktrace with more informations?
